from __future__ import annotations

import asyncio
import subprocess
from pathlib import Path

import pytest

from agentbraid.config import AgentBraidConfig
from agentbraid.errors import (
    RoutingError,
    RunNotFoundError,
    SecurityBoundaryError,
    StateError,
    WorktreeError,
)
from agentbraid.models import (
    CodexReasoningEffort,
    DeliveryMode,
    Executor,
    HostTaskResult,
    LocalizedRunNames,
    ProviderInvocationOutcome,
    RoutingMode,
    RunExecutionOverrides,
    RunPlan,
    RunReview,
    RunSnapshot,
    RunStatus,
    StartRunRequest,
    TaskKind,
    TaskOutcome,
    TaskSpec,
    TaskStatus,
    ValidationEvidence,
    WorkerResult,
    WorkspaceMode,
    WorkspaceSettings,
)
from agentbraid.providers.base import ProviderUsage, StructuredProviderResult
from agentbraid.service import AgentBraidService
from agentbraid.store import StateStore


class FakePlanner:
    def __init__(
        self,
        plan: RunPlan,
        *,
        worker_writes: bool = False,
        review_approved: bool = True,
    ) -> None:
        self.output_plan = plan
        self.worker_writes = worker_writes
        self.review_approved = review_approved
        self.requests: list[StartRunRequest] = []
        self.worker_tasks: list[TaskSpec] = []
        self.reviewed_runs: list[str] = []

    async def plan(
        self,
        request: StartRunRequest,
        workspace: Path,
    ) -> StructuredProviderResult[RunPlan]:
        self.requests.append(request)
        return StructuredProviderResult(
            output=self.output_plan,
            thread_id="lead-thread",
            usage=ProviderUsage(input_tokens=100, output_tokens=20),
            events=(),
            duration_seconds=1.5,
        )

    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del run_id
        self.worker_tasks.append(task)
        if not self.worker_writes:
            raise AssertionError("host-only test unexpectedly invoked a Codex worker")
        (workspace / "generated.txt").write_text("generated by codex\n", encoding="utf-8")
        return StructuredProviderResult(
            output=WorkerResult(
                outcome=TaskOutcome.SUCCEEDED,
                summary="Generated and validated the requested file.",
                changed_files=["generated.txt"],
                validations=[ValidationEvidence(command="test -f generated.txt", passed=True)],
                confidence=0.95,
            ),
            thread_id="worker-thread",
            usage=ProviderUsage(input_tokens=50, output_tokens=10),
            events=(),
            duration_seconds=0.5,
        )

    async def review_run(
        self,
        run: RunSnapshot,
        workspace: Path,
    ) -> StructuredProviderResult[RunReview]:
        assert workspace.is_dir()
        self.reviewed_runs.append(run.run_id)
        return StructuredProviderResult(
            output=RunReview(
                approved=self.review_approved,
                summary=(
                    "The integrated candidate meets all acceptance criteria."
                    if self.review_approved
                    else "The integrated candidate needs maintainer review."
                ),
                validations=[ValidationEvidence(command="git diff --check HEAD^", passed=True)],
            ),
            thread_id="lead-thread",
            usage=ProviderUsage(input_tokens=75, output_tokens=15),
            events=(),
            duration_seconds=0.75,
        )


class SequencedPlanner(FakePlanner):
    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del run_id
        self.worker_tasks.append(task)
        filename = f"{task.task_id}.txt"
        (workspace / filename).write_text(f"{task.task_id}\n", encoding="utf-8")
        return StructuredProviderResult(
            output=WorkerResult(
                outcome=TaskOutcome.SUCCEEDED,
                summary=f"Completed {task.task_id}.",
                changed_files=[filename],
                validations=[ValidationEvidence(command=f"test -f {filename}", passed=True)],
            ),
            thread_id=f"worker-{task.task_id}",
            usage=ProviderUsage(input_tokens=25, output_tokens=5),
            events=(),
            duration_seconds=0.25,
        )


class ParallelPlanner(FakePlanner):
    def __init__(self, plan: RunPlan) -> None:
        super().__init__(plan, worker_writes=True)
        self.active = 0
        self.max_active = 0

    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del workspace, run_id
        self.worker_tasks.append(task)
        self.active += 1
        self.max_active = max(self.max_active, self.active)
        await asyncio.sleep(0.02)
        self.active -= 1
        return StructuredProviderResult(
            output=WorkerResult(
                outcome=TaskOutcome.SUCCEEDED,
                summary=f"Completed {task.task_id}.",
            ),
            thread_id=f"worker-{task.task_id}",
            usage=ProviderUsage(input_tokens=10, output_tokens=2),
            events=(),
            duration_seconds=0.02,
        )


class CancelPlanner(FakePlanner):
    def __init__(self, plan: RunPlan) -> None:
        super().__init__(plan, worker_writes=True)
        self.started = asyncio.Event()
        self.run_id: str | None = None
        self.cancelled = False

    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del task, workspace
        self.run_id = run_id
        self.started.set()
        try:
            await asyncio.Future()
        except asyncio.CancelledError:
            self.cancelled = True
            raise
        raise AssertionError("unreachable")


class CancelPlanningPlanner(FakePlanner):
    def __init__(self, plan: RunPlan) -> None:
        super().__init__(plan)
        self.started = asyncio.Event()
        self.cancelled = False

    async def plan(
        self,
        request: StartRunRequest,
        workspace: Path,
    ) -> StructuredProviderResult[RunPlan]:
        del request, workspace
        self.started.set()
        try:
            await asyncio.Future()
        except asyncio.CancelledError:
            self.cancelled = True
            raise
        raise AssertionError("unreachable")


class CancelReviewPlanner(FakePlanner):
    def __init__(self, plan: RunPlan) -> None:
        super().__init__(plan, worker_writes=True)
        self.started = asyncio.Event()
        self.cancelled = False

    async def review_run(
        self,
        run: RunSnapshot,
        workspace: Path,
    ) -> StructuredProviderResult[RunReview]:
        del run, workspace
        self.started.set()
        try:
            await asyncio.Future()
        except asyncio.CancelledError:
            self.cancelled = True
            raise
        raise AssertionError("unreachable")


def make_config(
    tmp_path: Path,
    *,
    max_parallel_codex: int = 1,
    max_task_attempts: int = 2,
) -> AgentBraidConfig:
    state_dir = tmp_path.parent / f"{tmp_path.name}-state"
    return AgentBraidConfig(
        state_dir=state_dir,
        database_path=state_dir / "agentbraid.db",
        worktree_dir=state_dir / "worktrees",
        codex_model="gpt-test",
        max_parallel_codex=max_parallel_codex,
        max_task_attempts=max_task_attempts,
    )


def git(repository: Path, *arguments: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(repository), *arguments],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        raise AssertionError(completed.stderr)
    return completed.stdout.strip()


def initialize_repository(workspace: Path) -> None:
    git(workspace, "init", "-b", "main")
    git(workspace, "config", "user.name", "AgentBraid Test")
    git(workspace, "config", "user.email", "agentbraid@example.test")
    (workspace / "README.md").write_text("# Test\n", encoding="utf-8")
    git(workspace, "add", "README.md")
    git(workspace, "commit", "--signoff", "-m", "chore: initialize test repository")


def host_plan(*, mutates_workspace: bool = False) -> RunPlan:
    return RunPlan(
        summary="Delegate one bounded task to the active host.",
        tasks=[
            TaskSpec(
                task_id="host-task",
                title="Complete host task",
                instructions="Complete and validate the bounded host task.",
                kind=TaskKind.IMPLEMENTATION,
                preferred_executor=Executor.HOST,
                mutates_workspace=mutates_workspace,
                acceptance_criteria=["The task is validated."],
            )
        ],
        final_acceptance_criteria=["The host task succeeds."],
    )


def codex_plan() -> RunPlan:
    return RunPlan(
        summary="Assign one isolated implementation task to Codex.",
        tasks=[
            TaskSpec(
                task_id="codex-task",
                title="Generate file",
                instructions="Generate and validate generated.txt.",
                kind=TaskKind.IMPLEMENTATION,
                preferred_executor=Executor.CODEX,
                mutates_workspace=True,
                acceptance_criteria=["generated.txt exists."],
            )
        ],
        final_acceptance_criteria=["The Codex change is integrated."],
    )


def parallel_codex_plan() -> RunPlan:
    return RunPlan(
        summary="Execute independent read-only tasks in parallel.",
        tasks=[
            TaskSpec(
                task_id=task_id,
                title=f"Inspect {task_id}",
                instructions="Inspect without changing files.",
                kind=TaskKind.EXPLORATION,
                preferred_executor=Executor.CODEX,
                acceptance_criteria=["Inspection completes."],
                max_attempts=3,
            )
            for task_id in ("first", "second")
        ],
        final_acceptance_criteria=["Both inspections complete."],
    )


def dependent_codex_plan() -> RunPlan:
    child = TaskSpec(
        task_id="child",
        title="Complete child",
        instructions="Complete the child after its parent.",
        kind=TaskKind.IMPLEMENTATION,
        preferred_executor=Executor.CODEX,
        mutates_workspace=True,
        dependencies=["parent"],
        acceptance_criteria=["child.txt exists."],
    )
    parent = TaskSpec(
        task_id="parent",
        title="Complete parent",
        instructions="Complete the parent first.",
        kind=TaskKind.IMPLEMENTATION,
        preferred_executor=Executor.CODEX,
        mutates_workspace=True,
        acceptance_criteria=["parent.txt exists."],
    )
    return RunPlan(
        summary="Execute a parent-child mutation chain.",
        tasks=[child, parent],
        final_acceptance_criteria=["Both commits are integrated in dependency order."],
    )


@pytest.mark.asyncio
async def test_service_starts_run_and_tracks_host_capability(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    store = StateStore(config.database_path)
    planner = FakePlanner(host_plan())
    service = AgentBraidService(config, tmp_path, store=store, codex=planner)

    run = await service.start_run(
        StartRunRequest(goal="Complete the feature.", host_model="antigravity-test")
    )
    claimed = service.claim_host_task(run.run_id, "host-session")

    assert run.status == RunStatus.RUNNING
    assert run.request.workspace == str(tmp_path)
    assert run.lead_thread_id == "lead-thread"
    assert run.base_branch == "main"
    assert run.base_commit == git(tmp_path, "rev-parse", "HEAD")
    assert [usage.phase for usage in run.provider_usage] == ["planning"]
    assert run.provider_usage[0].outcome == ProviderInvocationOutcome.SUCCEEDED
    assert run.tasks[0].status == TaskStatus.READY
    assert claimed is not None
    assert claimed.status == TaskStatus.RUNNING
    capabilities = service.list_capabilities()
    assert [(item.executor, item.model) for item in capabilities] == [
        (Executor.CODEX, "gpt-test"),
        (Executor.HOST, "antigravity-test"),
    ]


@pytest.mark.asyncio
async def test_service_rejects_workspace_escape(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(config, tmp_path, codex=FakePlanner(host_plan()))

    with pytest.raises(SecurityBoundaryError, match="must match"):
        await service.start_run(StartRunRequest(goal="Escape.", workspace=str(tmp_path.parent)))


@pytest.mark.asyncio
async def test_service_rejects_nested_run(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setenv("AGENTBRAID_CHILD", "1")
    config = make_config(tmp_path)
    service = AgentBraidService(config, tmp_path, codex=FakePlanner(host_plan()))

    with pytest.raises(SecurityBoundaryError, match="nested"):
        await service.start_run(StartRunRequest(goal="Do not recurse."))


@pytest.mark.asyncio
async def test_service_submits_host_commit(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config, tmp_path, codex=FakePlanner(host_plan(mutates_workspace=True))
    )
    run = await service.start_run(StartRunRequest(goal="Edit and commit."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    assert claimed.worktree_path is not None
    worktree = Path(claimed.worktree_path)
    (worktree / "host.txt").write_text("host change\n", encoding="utf-8")
    git(worktree, "add", "host.txt")
    git(worktree, "commit", "--signoff", "-m", "feat: add host change")
    commit_sha = git(worktree, "rev-parse", "HEAD")

    completed = await service.submit_host_result(
        run.run_id,
        "host-task",
        "host-session",
        HostTaskResult(
            outcome=TaskOutcome.SUCCEEDED,
            summary="Change validated and committed.",
            changed_files=["host.txt"],
            validations=[ValidationEvidence(command="test -f host.txt", passed=True)],
            commit_sha=commit_sha,
        ),
    )

    assert completed.status == TaskStatus.SUCCEEDED
    assert completed.commit_sha == commit_sha
    assert service.get_run(run.run_id).status == RunStatus.COMPLETED
    integration_path = service.worktrees.integration_path(run.run_id)
    assert (integration_path / "host.txt").read_text(encoding="utf-8") == "host change\n"
    assert not (tmp_path / "host.txt").exists()
    host_capability = next(
        item for item in service.list_capabilities() if item.executor == Executor.HOST
    )
    assert host_capability.successes == 1


@pytest.mark.asyncio
async def test_service_executes_and_integrates_codex_worker(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = FakePlanner(codex_plan(), worker_writes=True)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Generate the requested file."))

    assert run.status == RunStatus.COMPLETED
    assert run.tasks[0].status == TaskStatus.SUCCEEDED
    assert run.tasks[0].commit_sha is not None
    assert run.tasks[0].worktree_path is not None
    assert [task.task_id for task in codex.worker_tasks] == ["codex-task"]
    assert codex.reviewed_runs == [run.run_id]
    assert [usage.phase for usage in run.provider_usage] == ["planning", "task", "review"]
    assert [usage.outcome for usage in run.provider_usage] == [
        ProviderInvocationOutcome.SUCCEEDED,
        ProviderInvocationOutcome.SUCCEEDED,
        ProviderInvocationOutcome.APPROVED,
    ]
    assert run.provider_usage[1].attempt == 1
    integration_path = service.worktrees.integration_path(run.run_id)
    assert (integration_path / "generated.txt").read_text(encoding="utf-8") == (
        "generated by codex\n"
    )
    assert not (tmp_path / "generated.txt").exists()

    with pytest.raises(SecurityBoundaryError, match="explicit confirmation"):
        service.apply_run(run.run_id, "yes")
    applied = service.apply_run(run.run_id, "apply-reviewed-run")

    assert applied.commit_sha == git(tmp_path, "rev-parse", "HEAD")
    assert (tmp_path / "generated.txt").read_text(encoding="utf-8") == "generated by codex\n"


@pytest.mark.asyncio
async def test_apply_rejects_changed_primary_branch(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    service = AgentBraidService(
        make_config(tmp_path),
        tmp_path,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )
    run = await service.start_run(StartRunRequest(goal="Prepare a reviewed change."))
    git(tmp_path, "switch", "-c", "other-branch")

    with pytest.raises(WorktreeError, match="branch changed"):
        service.apply_run(run.run_id, "apply-reviewed-run")


@pytest.mark.asyncio
async def test_non_mutating_host_cannot_dirty_shared_worktree(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    service = AgentBraidService(
        make_config(tmp_path),
        tmp_path,
        codex=FakePlanner(host_plan()),
    )
    run = await service.start_run(StartRunRequest(goal="Inspect without edits."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    assert claimed.worktree_path is not None
    (Path(claimed.worktree_path) / "README.md").write_text("changed\n", encoding="utf-8")

    with pytest.raises(StateError, match="read-only worktree"):
        await service.submit_host_result(
            run.run_id,
            "host-task",
            "host-session",
            HostTaskResult(outcome=TaskOutcome.SUCCEEDED, summary="Inspected."),
        )


@pytest.mark.asyncio
async def test_parallel_codex_setting_and_retry_ceiling_are_applied(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    planner = ParallelPlanner(parallel_codex_plan())
    service = AgentBraidService(
        make_config(tmp_path, max_parallel_codex=2, max_task_attempts=1),
        tmp_path,
        codex=planner,
    )

    run = await service.start_run(StartRunRequest(goal="Inspect in parallel."))

    assert run.status == RunStatus.COMPLETED
    assert planner.max_active == 2
    assert all(task.spec.max_attempts == 1 for task in run.tasks)


@pytest.mark.asyncio
async def test_planning_persists_localized_run_names(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    names = LocalizedRunNames.model_validate(
        {
            "en": "Inspect project README",
            "zh-TW": "檢查專案 README",
            "zh-CN": "检查项目 README",
        }
    )
    plan = host_plan().model_copy(update={"display_names": names})
    service = AgentBraidService(
        make_config(tmp_path),
        tmp_path,
        codex=FakePlanner(plan),
    )

    run = await service.start_run(StartRunRequest(goal="Inspect README."))

    assert run.display_names == names
    assert service.store.list_runs()[0].display_names == names
    assert run.request.goal == "Inspect README."


def test_saved_settings_and_run_overrides_resolve_into_snapshot(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    store = StateStore(config.database_path)
    store.upsert_workspace_settings(
        WorkspaceSettings(
            workspace=str(tmp_path),
            codex_binary="codex",
            codex_model="saved-codex",
            codex_reasoning_effort=CodexReasoningEffort.MEDIUM,
            host_model="saved-agy-label",
            delivery_mode=DeliveryMode.REPORT_ONLY,
            max_parallel_codex=2,
            max_task_attempts=3,
            codex_timeout_seconds=900,
            max_output_bytes=4 * 1024 * 1024,
            worktree_dir=str(config.worktree_dir),
        )
    )
    service = AgentBraidService(
        config,
        tmp_path,
        store=store,
        codex=FakePlanner(host_plan()),
    )

    run = service.create_run(
        StartRunRequest(
            goal="Resolve settings.",
            execution=RunExecutionOverrides(
                codex_model="run-codex",
                codex_reasoning_effort=CodexReasoningEffort.HIGH,
                routing_mode=RoutingMode.CODEX_ONLY,
                workspace_mode=WorkspaceMode.READ_ONLY,
                max_parallel_codex=3,
            ),
        )
    )

    assert run.execution_settings is not None
    assert run.execution_settings.codex_model == "run-codex"
    assert run.execution_settings.codex_reasoning_effort == CodexReasoningEffort.HIGH
    assert run.execution_settings.host_model == "saved-agy-label"
    assert run.execution_settings.routing_mode == RoutingMode.CODEX_ONLY
    assert run.execution_settings.delivery_mode == DeliveryMode.REPORT_ONLY
    assert run.execution_settings.workspace_mode == WorkspaceMode.READ_ONLY
    assert run.execution_settings.max_parallel_codex == 3
    assert run.execution_settings.max_task_attempts == 3
    assert run.execution_settings.codex_timeout_seconds == 900


@pytest.mark.asyncio
async def test_codex_only_routes_host_preference_to_codex(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    planner = ParallelPlanner(host_plan())
    service = AgentBraidService(make_config(tmp_path), tmp_path, codex=planner)

    run = await service.start_run(
        StartRunRequest(
            goal="Inspect without AGY execution.",
            execution=RunExecutionOverrides(
                routing_mode=RoutingMode.CODEX_ONLY,
                workspace_mode=WorkspaceMode.READ_ONLY,
            ),
        )
    )

    assert run.status == RunStatus.COMPLETED
    assert run.tasks[0].executor == Executor.CODEX
    assert [task.task_id for task in planner.worker_tasks] == ["host-task"]


@pytest.mark.asyncio
async def test_read_only_run_blocks_mutating_plan(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    store = StateStore(config.database_path)
    service = AgentBraidService(
        config,
        tmp_path,
        store=store,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )

    with pytest.raises(RoutingError, match="read-only"):
        await service.start_run(
            StartRunRequest(
                goal="Do not allow writes.",
                execution=RunExecutionOverrides(workspace_mode=WorkspaceMode.READ_ONLY),
            )
        )

    assert store.list_runs()[0].status == RunStatus.BLOCKED


@pytest.mark.asyncio
async def test_delete_run_removes_database_worktrees_and_merged_branches(
    tmp_path: Path,
) -> None:
    initialize_repository(tmp_path)
    service = AgentBraidService(
        make_config(tmp_path),
        tmp_path,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )
    run = await service.start_run(StartRunRequest(goal="Prepare disposable work."))
    service.apply_run(run.run_id, "apply-reviewed-run")
    run = service.get_run(run.run_id)
    worktree_paths = [Path(task.worktree_path) for task in run.tasks if task.worktree_path]
    worktree_paths.append(service.worktrees.integration_path(run.run_id))

    preview = service.preview_run_cleanup(run.run_id)
    result = service.delete_run(run.run_id)

    assert preview.deletable is True
    assert result.deleted is True
    assert all(not path.exists() for path in worktree_paths)
    assert git(tmp_path, "branch", "--list", run.integration_branch or "") == ""
    with pytest.raises(RunNotFoundError):
        service.get_run(run.run_id)


@pytest.mark.asyncio
async def test_delete_run_preserves_dirty_or_unmerged_work(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    service = AgentBraidService(
        make_config(tmp_path),
        tmp_path,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )
    run = await service.start_run(StartRunRequest(goal="Preserve unsafe cleanup targets."))
    integration_path = service.worktrees.integration_path(run.run_id)
    (integration_path / "uncommitted.txt").write_text("keep me\n", encoding="utf-8")

    preview = service.preview_run_cleanup(run.run_id)
    result = service.delete_run(run.run_id)

    assert preview.deletable is False
    assert preview.artifacts[0].kind == "database"
    assert preview.artifacts[0].removable is False
    assert any("not merged" in blocker for blocker in preview.blockers)
    assert any("worktree" in blocker for blocker in preview.blockers)
    assert result.deleted is False
    assert integration_path.exists()
    assert service.get_run(run.run_id).run_id == run.run_id


@pytest.mark.asyncio
async def test_concurrent_finalize_runs_review_once(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    store = StateStore(config.database_path)
    planner = FakePlanner(host_plan())
    service = AgentBraidService(config, tmp_path, store=store, codex=planner)
    run = await service.start_run(StartRunRequest(goal="Review once."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    store.submit_task_result(
        run.run_id,
        "host-task",
        HostTaskResult(outcome=TaskOutcome.SUCCEEDED, summary="Done."),
        claimed_by="host-session",
        worktree_path=claimed.worktree_path,
    )

    await asyncio.gather(
        service._finalize_if_ready(run.run_id),
        service._finalize_if_ready(run.run_id),
    )

    assert planner.reviewed_runs == [run.run_id]


@pytest.mark.asyncio
async def test_cancel_stops_active_codex_invocation(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    plan = parallel_codex_plan()
    planner = CancelPlanner(plan.model_copy(update={"tasks": [plan.tasks[0]]}))
    config = make_config(tmp_path)
    service = AgentBraidService(config, tmp_path, codex=planner)
    starting = asyncio.create_task(service.start_run(StartRunRequest(goal="Cancel active work.")))
    await planner.started.wait()
    assert planner.run_id is not None

    StateStore(config.database_path).cancel_run(planner.run_id)
    run = await starting

    assert planner.cancelled is True
    assert run.status == RunStatus.CANCELLED


@pytest.mark.asyncio
async def test_external_cancel_stops_planning_invocation(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    planner = CancelPlanningPlanner(host_plan())
    service = AgentBraidService(config, tmp_path, codex=planner)
    starting = asyncio.create_task(service.start_run(StartRunRequest(goal="Cancel planning.")))
    await planner.started.wait()
    summaries = StateStore(config.database_path).list_runs()
    assert len(summaries) == 1

    StateStore(config.database_path).cancel_run(summaries[0].run_id)
    run = await asyncio.wait_for(starting, timeout=2)

    assert planner.cancelled is True
    assert run.status == RunStatus.CANCELLED


@pytest.mark.asyncio
async def test_external_cancel_stops_review_invocation(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    planner = CancelReviewPlanner(codex_plan())
    service = AgentBraidService(config, tmp_path, codex=planner)
    starting = asyncio.create_task(service.start_run(StartRunRequest(goal="Cancel review.")))
    await planner.started.wait()
    summaries = StateStore(config.database_path).list_runs()
    assert len(summaries) == 1

    StateStore(config.database_path).cancel_run(summaries[0].run_id)
    run = await asyncio.wait_for(starting, timeout=2)

    assert planner.cancelled is True
    assert run.status == RunStatus.CANCELLED


@pytest.mark.asyncio
async def test_unsigned_host_commit_is_released_for_retry(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config,
        tmp_path,
        codex=FakePlanner(host_plan(mutates_workspace=True)),
    )
    run = await service.start_run(StartRunRequest(goal="Try an unsigned host change."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    assert claimed.worktree_path is not None
    worktree = Path(claimed.worktree_path)
    (worktree / "unsigned.txt").write_text("unsigned\n", encoding="utf-8")
    git(worktree, "add", "unsigned.txt")
    git(worktree, "commit", "-m", "feat: unsigned change")
    commit_sha = git(worktree, "rev-parse", "HEAD")

    retryable = await service.submit_host_result(
        run.run_id,
        "host-task",
        "host-session",
        HostTaskResult(
            outcome=TaskOutcome.SUCCEEDED,
            summary="Submitted without a signoff.",
            changed_files=["unsigned.txt"],
            validations=[ValidationEvidence(command="test -f unsigned.txt", passed=True)],
            commit_sha=commit_sha,
        ),
    )

    assert retryable.status == TaskStatus.READY
    assert retryable.result is not None
    assert retryable.result.outcome == TaskOutcome.FAILED
    reclaimed = service.claim_host_task(run.run_id, "host-session")
    assert reclaimed is not None
    assert reclaimed.commit_sha is None


@pytest.mark.asyncio
async def test_rejected_review_blocks_delivery(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = FakePlanner(codex_plan(), worker_writes=True, review_approved=False)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Generate but reject the candidate."))

    assert run.status == RunStatus.BLOCKED
    assert run.final_summary == "The integrated candidate needs maintainer review."
    with pytest.raises(StateError, match="complete final review"):
        service.apply_run(run.run_id, "apply-reviewed-run")


@pytest.mark.asyncio
async def test_report_only_run_cannot_be_applied(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config,
        tmp_path,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )
    run = await service.start_run(
        StartRunRequest(
            goal="Generate a report-only candidate.",
            delivery_mode=DeliveryMode.REPORT_ONLY,
        )
    )

    assert run.status == RunStatus.COMPLETED
    with pytest.raises(StateError, match="report-only"):
        service.apply_run(run.run_id, "apply-reviewed-run")


@pytest.mark.asyncio
async def test_codex_commits_integrate_in_dependency_order(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = SequencedPlanner(dependent_codex_plan(), worker_writes=True)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Execute the dependency chain."))

    assert run.status == RunStatus.COMPLETED
    assert [task.spec.task_id for task in run.tasks] == ["child", "parent"]
    assert all(task.status == TaskStatus.SUCCEEDED for task in run.tasks)
    assert [task.task_id for task in codex.worker_tasks] == ["parent", "child"]
    integration_path = service.worktrees.integration_path(run.run_id)
    subjects = git(integration_path, "log", "--reverse", "--format=%s").splitlines()
    parent_index = next(
        index for index, subject in enumerate(subjects) if "agentbraid(parent)" in subject
    )
    child_index = next(
        index for index, subject in enumerate(subjects) if "agentbraid(child)" in subject
    )
    assert parent_index < child_index
