from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from agentbraid.config import AgentBraidConfig
from agentbraid.errors import SecurityBoundaryError, StateError
from agentbraid.models import (
    DeliveryMode,
    Executor,
    HostTaskResult,
    RunPlan,
    RunReview,
    RunSnapshot,
    RunStatus,
    StartRunRequest,
    TaskKind,
    TaskOutcome,
    TaskSpec,
    TaskStatus,
    ValidationEvidence,
    WorkerResult,
)
from agentbraid.providers.base import ProviderUsage, StructuredProviderResult
from agentbraid.service import AgentBraidService
from agentbraid.store import StateStore


class FakePlanner:
    def __init__(
        self,
        plan: RunPlan,
        *,
        worker_writes: bool = False,
        review_approved: bool = True,
    ) -> None:
        self.output_plan = plan
        self.worker_writes = worker_writes
        self.review_approved = review_approved
        self.requests: list[StartRunRequest] = []
        self.worker_tasks: list[TaskSpec] = []
        self.reviewed_runs: list[str] = []

    async def plan(
        self,
        request: StartRunRequest,
        workspace: Path,
    ) -> StructuredProviderResult[RunPlan]:
        self.requests.append(request)
        return StructuredProviderResult(
            output=self.output_plan,
            thread_id="lead-thread",
            usage=ProviderUsage(input_tokens=100, output_tokens=20),
            events=(),
            duration_seconds=1.5,
        )

    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del run_id
        self.worker_tasks.append(task)
        if not self.worker_writes:
            raise AssertionError("host-only test unexpectedly invoked a Codex worker")
        (workspace / "generated.txt").write_text("generated by codex\n", encoding="utf-8")
        return StructuredProviderResult(
            output=WorkerResult(
                outcome=TaskOutcome.SUCCEEDED,
                summary="Generated and validated the requested file.",
                changed_files=["generated.txt"],
                validations=[ValidationEvidence(command="test -f generated.txt", passed=True)],
                confidence=0.95,
            ),
            thread_id="worker-thread",
            usage=ProviderUsage(input_tokens=50, output_tokens=10),
            events=(),
            duration_seconds=0.5,
        )

    async def review_run(
        self,
        run: RunSnapshot,
        workspace: Path,
    ) -> StructuredProviderResult[RunReview]:
        assert workspace.is_dir()
        self.reviewed_runs.append(run.run_id)
        return StructuredProviderResult(
            output=RunReview(
                approved=self.review_approved,
                summary=(
                    "The integrated candidate meets all acceptance criteria."
                    if self.review_approved
                    else "The integrated candidate needs maintainer review."
                ),
                validations=[ValidationEvidence(command="git diff --check HEAD^", passed=True)],
            ),
            thread_id="lead-thread",
            usage=ProviderUsage(input_tokens=75, output_tokens=15),
            events=(),
            duration_seconds=0.75,
        )


class SequencedPlanner(FakePlanner):
    async def execute_task(
        self,
        task: TaskSpec,
        workspace: Path,
        *,
        run_id: str,
    ) -> StructuredProviderResult[WorkerResult]:
        del run_id
        self.worker_tasks.append(task)
        filename = f"{task.task_id}.txt"
        (workspace / filename).write_text(f"{task.task_id}\n", encoding="utf-8")
        return StructuredProviderResult(
            output=WorkerResult(
                outcome=TaskOutcome.SUCCEEDED,
                summary=f"Completed {task.task_id}.",
                changed_files=[filename],
                validations=[ValidationEvidence(command=f"test -f {filename}", passed=True)],
            ),
            thread_id=f"worker-{task.task_id}",
            usage=ProviderUsage(input_tokens=25, output_tokens=5),
            events=(),
            duration_seconds=0.25,
        )


def make_config(tmp_path: Path) -> AgentBraidConfig:
    state_dir = tmp_path.parent / f"{tmp_path.name}-state"
    return AgentBraidConfig(
        state_dir=state_dir,
        database_path=state_dir / "agentbraid.db",
        worktree_dir=state_dir / "worktrees",
        codex_model="gpt-test",
    )


def git(repository: Path, *arguments: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(repository), *arguments],
        capture_output=True,
        check=False,
        text=True,
    )
    if completed.returncode != 0:
        raise AssertionError(completed.stderr)
    return completed.stdout.strip()


def initialize_repository(workspace: Path) -> None:
    git(workspace, "init", "-b", "main")
    git(workspace, "config", "user.name", "AgentBraid Test")
    git(workspace, "config", "user.email", "agentbraid@example.test")
    (workspace / "README.md").write_text("# Test\n", encoding="utf-8")
    git(workspace, "add", "README.md")
    git(workspace, "commit", "--signoff", "-m", "chore: initialize test repository")


def host_plan(*, mutates_workspace: bool = False) -> RunPlan:
    return RunPlan(
        summary="Delegate one bounded task to the active host.",
        tasks=[
            TaskSpec(
                task_id="host-task",
                title="Complete host task",
                instructions="Complete and validate the bounded host task.",
                kind=TaskKind.IMPLEMENTATION,
                preferred_executor=Executor.HOST,
                mutates_workspace=mutates_workspace,
                acceptance_criteria=["The task is validated."],
            )
        ],
        final_acceptance_criteria=["The host task succeeds."],
    )


def codex_plan() -> RunPlan:
    return RunPlan(
        summary="Assign one isolated implementation task to Codex.",
        tasks=[
            TaskSpec(
                task_id="codex-task",
                title="Generate file",
                instructions="Generate and validate generated.txt.",
                kind=TaskKind.IMPLEMENTATION,
                preferred_executor=Executor.CODEX,
                mutates_workspace=True,
                acceptance_criteria=["generated.txt exists."],
            )
        ],
        final_acceptance_criteria=["The Codex change is integrated."],
    )


def dependent_codex_plan() -> RunPlan:
    child = TaskSpec(
        task_id="child",
        title="Complete child",
        instructions="Complete the child after its parent.",
        kind=TaskKind.IMPLEMENTATION,
        preferred_executor=Executor.CODEX,
        mutates_workspace=True,
        dependencies=["parent"],
        acceptance_criteria=["child.txt exists."],
    )
    parent = TaskSpec(
        task_id="parent",
        title="Complete parent",
        instructions="Complete the parent first.",
        kind=TaskKind.IMPLEMENTATION,
        preferred_executor=Executor.CODEX,
        mutates_workspace=True,
        acceptance_criteria=["parent.txt exists."],
    )
    return RunPlan(
        summary="Execute a parent-child mutation chain.",
        tasks=[child, parent],
        final_acceptance_criteria=["Both commits are integrated in dependency order."],
    )


@pytest.mark.asyncio
async def test_service_starts_run_and_tracks_host_capability(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    store = StateStore(config.database_path)
    planner = FakePlanner(host_plan())
    service = AgentBraidService(config, tmp_path, store=store, codex=planner)

    run = await service.start_run(
        StartRunRequest(goal="Complete the feature.", host_model="antigravity-test")
    )
    claimed = service.claim_host_task(run.run_id, "host-session")

    assert run.status == RunStatus.RUNNING
    assert run.request.workspace == str(tmp_path)
    assert run.lead_thread_id == "lead-thread"
    assert run.tasks[0].status == TaskStatus.READY
    assert claimed is not None
    assert claimed.status == TaskStatus.RUNNING
    capabilities = service.list_capabilities()
    assert [(item.executor, item.model) for item in capabilities] == [
        (Executor.CODEX, "gpt-test"),
        (Executor.HOST, "antigravity-test"),
    ]


@pytest.mark.asyncio
async def test_service_rejects_workspace_escape(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(config, tmp_path, codex=FakePlanner(host_plan()))

    with pytest.raises(SecurityBoundaryError, match="must match"):
        await service.start_run(StartRunRequest(goal="Escape.", workspace=str(tmp_path.parent)))


@pytest.mark.asyncio
async def test_service_rejects_nested_run(
    monkeypatch: pytest.MonkeyPatch,
    tmp_path: Path,
) -> None:
    monkeypatch.setenv("AGENTBRAID_CHILD", "1")
    config = make_config(tmp_path)
    service = AgentBraidService(config, tmp_path, codex=FakePlanner(host_plan()))

    with pytest.raises(SecurityBoundaryError, match="nested"):
        await service.start_run(StartRunRequest(goal="Do not recurse."))


@pytest.mark.asyncio
async def test_service_submits_host_commit(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config, tmp_path, codex=FakePlanner(host_plan(mutates_workspace=True))
    )
    run = await service.start_run(StartRunRequest(goal="Edit and commit."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    assert claimed.worktree_path is not None
    worktree = Path(claimed.worktree_path)
    (worktree / "host.txt").write_text("host change\n", encoding="utf-8")
    git(worktree, "add", "host.txt")
    git(worktree, "commit", "--signoff", "-m", "feat: add host change")
    commit_sha = git(worktree, "rev-parse", "HEAD")

    completed = await service.submit_host_result(
        run.run_id,
        "host-task",
        "host-session",
        HostTaskResult(
            outcome=TaskOutcome.SUCCEEDED,
            summary="Change validated and committed.",
            changed_files=["host.txt"],
            validations=[ValidationEvidence(command="test -f host.txt", passed=True)],
            commit_sha=commit_sha,
        ),
    )

    assert completed.status == TaskStatus.SUCCEEDED
    assert completed.commit_sha == commit_sha
    assert service.get_run(run.run_id).status == RunStatus.COMPLETED
    integration_path = service.worktrees.integration_path(run.run_id)
    assert (integration_path / "host.txt").read_text(encoding="utf-8") == "host change\n"
    assert not (tmp_path / "host.txt").exists()
    host_capability = next(
        item for item in service.list_capabilities() if item.executor == Executor.HOST
    )
    assert host_capability.successes == 1


@pytest.mark.asyncio
async def test_service_executes_and_integrates_codex_worker(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = FakePlanner(codex_plan(), worker_writes=True)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Generate the requested file."))

    assert run.status == RunStatus.COMPLETED
    assert run.tasks[0].status == TaskStatus.SUCCEEDED
    assert run.tasks[0].commit_sha is not None
    assert run.tasks[0].worktree_path is not None
    assert [task.task_id for task in codex.worker_tasks] == ["codex-task"]
    assert codex.reviewed_runs == [run.run_id]
    integration_path = service.worktrees.integration_path(run.run_id)
    assert (integration_path / "generated.txt").read_text(encoding="utf-8") == (
        "generated by codex\n"
    )
    assert not (tmp_path / "generated.txt").exists()

    applied = service.apply_run(run.run_id)

    assert applied.commit_sha == git(tmp_path, "rev-parse", "HEAD")
    assert (tmp_path / "generated.txt").read_text(encoding="utf-8") == "generated by codex\n"


@pytest.mark.asyncio
async def test_unsigned_host_commit_is_released_for_retry(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config,
        tmp_path,
        codex=FakePlanner(host_plan(mutates_workspace=True)),
    )
    run = await service.start_run(StartRunRequest(goal="Try an unsigned host change."))
    claimed = service.claim_host_task(run.run_id, "host-session")
    assert claimed is not None
    assert claimed.worktree_path is not None
    worktree = Path(claimed.worktree_path)
    (worktree / "unsigned.txt").write_text("unsigned\n", encoding="utf-8")
    git(worktree, "add", "unsigned.txt")
    git(worktree, "commit", "-m", "feat: unsigned change")
    commit_sha = git(worktree, "rev-parse", "HEAD")

    retryable = await service.submit_host_result(
        run.run_id,
        "host-task",
        "host-session",
        HostTaskResult(
            outcome=TaskOutcome.SUCCEEDED,
            summary="Submitted without a signoff.",
            changed_files=["unsigned.txt"],
            validations=[ValidationEvidence(command="test -f unsigned.txt", passed=True)],
            commit_sha=commit_sha,
        ),
    )

    assert retryable.status == TaskStatus.READY
    assert retryable.result is not None
    assert retryable.result.outcome == TaskOutcome.FAILED
    reclaimed = service.claim_host_task(run.run_id, "host-session")
    assert reclaimed is not None
    assert reclaimed.commit_sha is None


@pytest.mark.asyncio
async def test_rejected_review_blocks_delivery(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = FakePlanner(codex_plan(), worker_writes=True, review_approved=False)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Generate but reject the candidate."))

    assert run.status == RunStatus.BLOCKED
    assert run.final_summary == "The integrated candidate needs maintainer review."
    with pytest.raises(StateError, match="complete final review"):
        service.apply_run(run.run_id)


@pytest.mark.asyncio
async def test_report_only_run_cannot_be_applied(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    service = AgentBraidService(
        config,
        tmp_path,
        codex=FakePlanner(codex_plan(), worker_writes=True),
    )
    run = await service.start_run(
        StartRunRequest(
            goal="Generate a report-only candidate.",
            delivery_mode=DeliveryMode.REPORT_ONLY,
        )
    )

    assert run.status == RunStatus.COMPLETED
    with pytest.raises(StateError, match="report-only"):
        service.apply_run(run.run_id)


@pytest.mark.asyncio
async def test_codex_commits_integrate_in_dependency_order(tmp_path: Path) -> None:
    initialize_repository(tmp_path)
    config = make_config(tmp_path)
    codex = SequencedPlanner(dependent_codex_plan(), worker_writes=True)
    service = AgentBraidService(config, tmp_path, codex=codex)

    run = await service.start_run(StartRunRequest(goal="Execute the dependency chain."))

    assert run.status == RunStatus.COMPLETED
    assert [task.spec.task_id for task in run.tasks] == ["child", "parent"]
    assert all(task.status == TaskStatus.SUCCEEDED for task in run.tasks)
    assert [task.task_id for task in codex.worker_tasks] == ["parent", "child"]
    integration_path = service.worktrees.integration_path(run.run_id)
    subjects = git(integration_path, "log", "--reverse", "--format=%s").splitlines()
    parent_index = next(
        index for index, subject in enumerate(subjects) if "agentbraid(parent)" in subject
    )
    child_index = next(
        index for index, subject in enumerate(subjects) if "agentbraid(child)" in subject
    )
    assert parent_index < child_index
